name: flutter_zalo_login
description: A Flutter plugin for allowing users to authenticate with native Android &amp; iOS Zalo login SDKs.
version: 0.1.3
homepage: https://github.com/duythien0912/flutter_zalo_login

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.neun.flutter_zalo_login.flutter_zalo_login
    pluginClass: FlutterZaloLoginPlugin

